var wms_layers = [];
var format_sungai_int_jalan_0 = new ol.format.GeoJSON();
var features_sungai_int_jalan_0 = format_sungai_int_jalan_0.readFeatures(json_sungai_int_jalan_0, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_sungai_int_jalan_0 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_sungai_int_jalan_0.addFeatures(features_sungai_int_jalan_0);var lyr_sungai_int_jalan_0 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_sungai_int_jalan_0, 
                style: style_sungai_int_jalan_0,
                title: '<img src="styles/legend/sungai_int_jalan_0.png" /> sungai_int_jalan'
            });var format_sungai_buffer_1 = new ol.format.GeoJSON();
var features_sungai_buffer_1 = format_sungai_buffer_1.readFeatures(json_sungai_buffer_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_sungai_buffer_1 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_sungai_buffer_1.addFeatures(features_sungai_buffer_1);var lyr_sungai_buffer_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_sungai_buffer_1, 
                style: style_sungai_buffer_1,
                title: '<img src="styles/legend/sungai_buffer_1.png" /> sungai_buffer'
            });var format_PL_bantul_2 = new ol.format.GeoJSON();
var features_PL_bantul_2 = format_PL_bantul_2.readFeatures(json_PL_bantul_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_PL_bantul_2 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_PL_bantul_2.addFeatures(features_PL_bantul_2);var lyr_PL_bantul_2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_PL_bantul_2, 
                style: style_PL_bantul_2,
                title: '<img src="styles/legend/PL_bantul_2.png" /> PL_bantul'
            });var format_jalan_buffer_3 = new ol.format.GeoJSON();
var features_jalan_buffer_3 = format_jalan_buffer_3.readFeatures(json_jalan_buffer_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_jalan_buffer_3 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_jalan_buffer_3.addFeatures(features_jalan_buffer_3);var lyr_jalan_buffer_3 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_jalan_buffer_3, 
                style: style_jalan_buffer_3,
                title: '<img src="styles/legend/jalan_buffer_3.png" /> jalan_buffer'
            });var format_jalan_bantul_4 = new ol.format.GeoJSON();
var features_jalan_bantul_4 = format_jalan_bantul_4.readFeatures(json_jalan_bantul_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_jalan_bantul_4 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_jalan_bantul_4.addFeatures(features_jalan_bantul_4);var lyr_jalan_bantul_4 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_jalan_bantul_4, 
                style: style_jalan_bantul_4,
                title: '<img src="styles/legend/jalan_bantul_4.png" /> jalan_bantul'
            });var format_Hasil_lokasi_5 = new ol.format.GeoJSON();
var features_Hasil_lokasi_5 = format_Hasil_lokasi_5.readFeatures(json_Hasil_lokasi_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Hasil_lokasi_5 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_Hasil_lokasi_5.addFeatures(features_Hasil_lokasi_5);var lyr_Hasil_lokasi_5 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Hasil_lokasi_5, 
                style: style_Hasil_lokasi_5,
                title: '<img src="styles/legend/Hasil_lokasi_5.png" /> Hasil_lokasi'
            });var format_bufferjln_6 = new ol.format.GeoJSON();
var features_bufferjln_6 = format_bufferjln_6.readFeatures(json_bufferjln_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_bufferjln_6 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_bufferjln_6.addFeatures(features_bufferjln_6);var lyr_bufferjln_6 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_bufferjln_6, 
                style: style_bufferjln_6,
                title: '<img src="styles/legend/bufferjln_6.png" /> bufferjln'
            });var format_buffer_jalan_7 = new ol.format.GeoJSON();
var features_buffer_jalan_7 = format_buffer_jalan_7.readFeatures(json_buffer_jalan_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_buffer_jalan_7 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_buffer_jalan_7.addFeatures(features_buffer_jalan_7);var lyr_buffer_jalan_7 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_buffer_jalan_7, 
                style: style_buffer_jalan_7,
                title: '<img src="styles/legend/buffer_jalan_7.png" /> buffer_jalan'
            });

lyr_sungai_int_jalan_0.setVisible(true);lyr_sungai_buffer_1.setVisible(true);lyr_PL_bantul_2.setVisible(true);lyr_jalan_buffer_3.setVisible(true);lyr_jalan_bantul_4.setVisible(true);lyr_Hasil_lokasi_5.setVisible(true);lyr_bufferjln_6.setVisible(true);lyr_buffer_jalan_7.setVisible(true);
var layersList = [lyr_sungai_int_jalan_0,lyr_sungai_buffer_1,lyr_PL_bantul_2,lyr_jalan_buffer_3,lyr_jalan_bantul_4,lyr_Hasil_lokasi_5,lyr_bufferjln_6,lyr_buffer_jalan_7];
lyr_sungai_int_jalan_0.set('fieldAliases', {'FID_sungai': 'FID_sungai', 'FID_Bantul': 'FID_Bantul', 'PROVINSI': 'PROVINSI', 'KODE_KAB': 'KODE_KAB', 'SHAPE_LENG': 'SHAPE_LENG', 'KODE_PROP': 'KODE_PROP', 'KABUPATEN': 'KABUPATEN', 'AREA': 'AREA', 'PERIMETER': 'PERIMETER', 'HECTARES': 'HECTARES', 'SHAPE_LE_1': 'SHAPE_LE_1', 'SHAPE_AREA': 'SHAPE_AREA', 'FID_penggu': 'FID_penggu', 'FID_Peta_P': 'FID_Peta_P', 'PL': 'PL', 'Shape_Ar_1': 'Shape_Ar_1', 'Peruntukan': 'Peruntukan', 'Keterangan': 'Keterangan', 'KW': 'KW', 'WA': 'WA', 'TA': 'TA', 'DH': 'DH', 'LU': 'LU', 'KW_1': 'KW_1', 'WA_1': 'WA_1', 'TA_1': 'TA_1', 'DH_1': 'DH_1', 'SHAPE_Ar_2': 'SHAPE_Ar_2', 'BUFF_DIST': 'BUFF_DIST', 'ORIG_FID': 'ORIG_FID', 'FID_jalan_': 'FID_jalan_', 'FID_Bant_1': 'FID_Bant_1', 'PROVINSI_1': 'PROVINSI_1', 'KODE_KAB_1': 'KODE_KAB_1', 'SHAPE_LE_2': 'SHAPE_LE_2', 'KODE_PRO_1': 'KODE_PRO_1', 'KABUPATE_1': 'KABUPATE_1', 'AREA_1': 'AREA_1', 'PERIMETE_1': 'PERIMETE_1', 'HECTARES_1': 'HECTARES_1', 'SHAPE_LE_3': 'SHAPE_LE_3', 'SHAPE_AR_3': 'SHAPE_AR_3', 'FID_jalan1': 'FID_jalan1', 'LAYER': 'LAYER', 'KETERANG_1': 'KETERANG_1', 'LENGTH_FEE': 'LENGTH_FEE', 'SHAPE_LE_4': 'SHAPE_LE_4', 'SHAPE_LE_5': 'SHAPE_LE_5', 'BUFF_DIS_1': 'BUFF_DIS_1', 'ORIG_FID_1': 'ORIG_FID_1', });
lyr_sungai_buffer_1.set('fieldAliases', {'FID_Bantul': 'FID_Bantul', 'PROVINSI': 'PROVINSI', 'KODE_KAB': 'KODE_KAB', 'SHAPE_LENG': 'SHAPE_LENG', 'KODE_PROP': 'KODE_PROP', 'KABUPATEN': 'KABUPATEN', 'AREA': 'AREA', 'PERIMETER': 'PERIMETER', 'HECTARES': 'HECTARES', 'SHAPE_LE_1': 'SHAPE_LE_1', 'SHAPE_AREA': 'SHAPE_AREA', 'FID_penggu': 'FID_penggu', 'FID_Peta_P': 'FID_Peta_P', 'PL': 'PL', 'Shape_Ar_1': 'Shape_Ar_1', 'Peruntukan': 'Peruntukan', 'Keterangan': 'Keterangan', 'KW': 'KW', 'WA': 'WA', 'TA': 'TA', 'DH': 'DH', 'LU': 'LU', 'KW_1': 'KW_1', 'WA_1': 'WA_1', 'TA_1': 'TA_1', 'DH_1': 'DH_1', 'SHAPE_Ar_2': 'SHAPE_Ar_2', 'BUFF_DIST': 'BUFF_DIST', 'ORIG_FID': 'ORIG_FID', });
lyr_PL_bantul_2.set('fieldAliases', {'FID_Bantul': 'FID_Bantul', 'PROVINSI': 'PROVINSI', 'KODE_KAB': 'KODE_KAB', 'SHAPE_LENG': 'SHAPE_LENG', 'KODE_PROP': 'KODE_PROP', 'KABUPATEN': 'KABUPATEN', 'AREA': 'AREA', 'PERIMETER': 'PERIMETER', 'HECTARES': 'HECTARES', 'SHAPE_LE_1': 'SHAPE_LE_1', 'SHAPE_AREA': 'SHAPE_AREA', 'FID_penggu': 'FID_penggu', 'FID_Peta_P': 'FID_Peta_P', 'PL': 'PL', 'Shape_Ar_1': 'Shape_Ar_1', 'Peruntukan': 'Peruntukan', 'Keterangan': 'Keterangan', 'KW': 'KW', 'WA': 'WA', 'TA': 'TA', 'DH': 'DH', 'LU': 'LU', 'KW_1': 'KW_1', 'WA_1': 'WA_1', 'TA_1': 'TA_1', 'DH_1': 'DH_1', 'SHAPE_Ar_2': 'SHAPE_Ar_2', 'BOBOT': 'BOBOT', 'BBT5': 'BBT5', });
lyr_jalan_buffer_3.set('fieldAliases', {'FID_Bantul': 'FID_Bantul', 'PROVINSI': 'PROVINSI', 'KODE_KAB': 'KODE_KAB', 'SHAPE_LENG': 'SHAPE_LENG', 'KODE_PROP': 'KODE_PROP', 'KABUPATEN': 'KABUPATEN', 'AREA': 'AREA', 'PERIMETER': 'PERIMETER', 'HECTARES': 'HECTARES', 'SHAPE_LE_1': 'SHAPE_LE_1', 'SHAPE_AREA': 'SHAPE_AREA', 'FID_jalan_': 'FID_jalan_', 'LAYER': 'LAYER', 'KETERANGAN': 'KETERANGAN', 'LENGTH_FEE': 'LENGTH_FEE', 'SHAPE_LE_2': 'SHAPE_LE_2', 'SHAPE_LE_3': 'SHAPE_LE_3', 'BUFF_DIST': 'BUFF_DIST', 'ORIG_FID': 'ORIG_FID', });
lyr_jalan_bantul_4.set('fieldAliases', {'FID_Bantul': 'FID_Bantul', 'PROVINSI': 'PROVINSI', 'KODE_KAB': 'KODE_KAB', 'SHAPE_LENG': 'SHAPE_LENG', 'KODE_PROP': 'KODE_PROP', 'KABUPATEN': 'KABUPATEN', 'AREA': 'AREA', 'PERIMETER': 'PERIMETER', 'HECTARES': 'HECTARES', 'SHAPE_LE_1': 'SHAPE_LE_1', 'SHAPE_AREA': 'SHAPE_AREA', 'FID_jalan_': 'FID_jalan_', 'LAYER': 'LAYER', 'KETERANGAN': 'KETERANGAN', 'LENGTH_FEE': 'LENGTH_FEE', 'SHAPE_LE_2': 'SHAPE_LE_2', 'SHAPE_LE_3': 'SHAPE_LE_3', });
lyr_Hasil_lokasi_5.set('fieldAliases', {'FID_PL_ban': 'FID_PL_ban', 'FID_Bantul': 'FID_Bantul', 'PROVINSI': 'PROVINSI', 'KODE_KAB': 'KODE_KAB', 'SHAPE_LENG': 'SHAPE_LENG', 'KODE_PROP': 'KODE_PROP', 'KABUPATEN': 'KABUPATEN', 'AREA': 'AREA', 'PERIMETER': 'PERIMETER', 'HECTARES': 'HECTARES', 'SHAPE_LE_1': 'SHAPE_LE_1', 'SHAPE_AREA': 'SHAPE_AREA', 'FID_penggu': 'FID_penggu', 'FID_Peta_P': 'FID_Peta_P', 'PL': 'PL', 'Shape_Ar_1': 'Shape_Ar_1', 'Peruntukan': 'Peruntukan', 'Keterangan': 'Keterangan', 'KW': 'KW', 'WA': 'WA', 'TA': 'TA', 'DH': 'DH', 'LU': 'LU', 'KW_1': 'KW_1', 'WA_1': 'WA_1', 'TA_1': 'TA_1', 'DH_1': 'DH_1', 'SHAPE_Ar_2': 'SHAPE_Ar_2', 'BOBOT': 'BOBOT', 'BBT5': 'BBT5', 'FID_sungai': 'FID_sungai', 'FID_sung_1': 'FID_sung_1', 'FID_Bant_1': 'FID_Bant_1', 'PROVINSI_1': 'PROVINSI_1', 'KODE_KAB_1': 'KODE_KAB_1', 'SHAPE_LE_2': 'SHAPE_LE_2', 'KODE_PRO_1': 'KODE_PRO_1', 'KABUPATE_1': 'KABUPATE_1', 'AREA_1': 'AREA_1', 'PERIMETE_1': 'PERIMETE_1', 'HECTARES_1': 'HECTARES_1', 'SHAPE_LE_3': 'SHAPE_LE_3', 'SHAPE_AR_3': 'SHAPE_AR_3', 'FID_peng_1': 'FID_peng_1', 'FID_Peta_1': 'FID_Peta_1', 'PL_1': 'PL_1', 'Shape_Ar_4': 'Shape_Ar_4', 'Peruntuk_1': 'Peruntuk_1', 'Keterang_1': 'Keterang_1', 'KW_12': 'KW_12', 'WA_12': 'WA_12', 'TA_12': 'TA_12', 'DH_12': 'DH_12', 'LU_1': 'LU_1', 'KW_12_13': 'KW_12_13', 'WA_12_13': 'WA_12_13', 'TA_12_13': 'TA_12_13', 'DH_12_13': 'DH_12_13', 'SHAPE_Ar_5': 'SHAPE_Ar_5', 'BUFF_DIST': 'BUFF_DIST', 'ORIG_FID': 'ORIG_FID', 'FID_jalan_': 'FID_jalan_', 'FID_Bant_2': 'FID_Bant_2', 'PROVINSI_2': 'PROVINSI_2', 'KODE_KAB_2': 'KODE_KAB_2', 'SHAPE_LE_4': 'SHAPE_LE_4', 'KODE_PRO_2': 'KODE_PRO_2', 'KABUPATE_2': 'KABUPATE_2', 'AREA_12': 'AREA_12', 'PERIMETE_2': 'PERIMETE_2', 'HECTARES_2': 'HECTARES_2', 'SHAPE_LE_5': 'SHAPE_LE_5', 'SHAPE_AR_6': 'SHAPE_AR_6', 'FID_jalan1': 'FID_jalan1', 'LAYER': 'LAYER', 'KETERANG_2': 'KETERANG_2', 'LENGTH_FEE': 'LENGTH_FEE', 'SHAPE_LE_6': 'SHAPE_LE_6', 'SHAPE_LE_7': 'SHAPE_LE_7', 'BUFF_DIS_1': 'BUFF_DIS_1', 'ORIG_FID_1': 'ORIG_FID_1', });
lyr_bufferjln_6.set('fieldAliases', {'FID_Bantul': 'FID_Bantul', 'PROVINSI': 'PROVINSI', 'KODE_KAB': 'KODE_KAB', 'SHAPE_LENG': 'SHAPE_LENG', 'KODE_PROP': 'KODE_PROP', 'KABUPATEN': 'KABUPATEN', 'AREA': 'AREA', 'PERIMETER': 'PERIMETER', 'HECTARES': 'HECTARES', 'SHAPE_LE_1': 'SHAPE_LE_1', 'SHAPE_AREA': 'SHAPE_AREA', 'FID_jalan_': 'FID_jalan_', 'LAYER': 'LAYER', 'KETERANGAN': 'KETERANGAN', 'LENGTH_FEE': 'LENGTH_FEE', 'SHAPE_LE_2': 'SHAPE_LE_2', 'SHAPE_LE_3': 'SHAPE_LE_3', });
lyr_buffer_jalan_7.set('fieldAliases', {'FID_Bantul': 'FID_Bantul', 'PROVINSI': 'PROVINSI', 'KODE_KAB': 'KODE_KAB', 'SHAPE_LENG': 'SHAPE_LENG', 'KODE_PROP': 'KODE_PROP', 'KABUPATEN': 'KABUPATEN', 'AREA': 'AREA', 'PERIMETER': 'PERIMETER', 'HECTARES': 'HECTARES', 'SHAPE_LE_1': 'SHAPE_LE_1', 'SHAPE_AREA': 'SHAPE_AREA', 'FID_jalan_': 'FID_jalan_', 'LAYER': 'LAYER', 'KETERANGAN': 'KETERANGAN', 'LENGTH_FEE': 'LENGTH_FEE', 'SHAPE_LE_2': 'SHAPE_LE_2', 'SHAPE_LE_3': 'SHAPE_LE_3', 'BUFF_DIST': 'BUFF_DIST', 'ORIG_FID': 'ORIG_FID', });
lyr_sungai_int_jalan_0.set('fieldImages', {'FID_sungai': 'TextEdit', 'FID_Bantul': 'TextEdit', 'PROVINSI': 'TextEdit', 'KODE_KAB': 'TextEdit', 'SHAPE_LENG': 'TextEdit', 'KODE_PROP': 'TextEdit', 'KABUPATEN': 'TextEdit', 'AREA': 'TextEdit', 'PERIMETER': 'TextEdit', 'HECTARES': 'TextEdit', 'SHAPE_LE_1': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'FID_penggu': 'TextEdit', 'FID_Peta_P': 'TextEdit', 'PL': 'TextEdit', 'Shape_Ar_1': 'TextEdit', 'Peruntukan': 'TextEdit', 'Keterangan': 'TextEdit', 'KW': 'TextEdit', 'WA': 'TextEdit', 'TA': 'TextEdit', 'DH': 'TextEdit', 'LU': 'TextEdit', 'KW_1': 'TextEdit', 'WA_1': 'TextEdit', 'TA_1': 'TextEdit', 'DH_1': 'TextEdit', 'SHAPE_Ar_2': 'TextEdit', 'BUFF_DIST': 'TextEdit', 'ORIG_FID': 'TextEdit', 'FID_jalan_': 'TextEdit', 'FID_Bant_1': 'TextEdit', 'PROVINSI_1': 'TextEdit', 'KODE_KAB_1': 'TextEdit', 'SHAPE_LE_2': 'TextEdit', 'KODE_PRO_1': 'TextEdit', 'KABUPATE_1': 'TextEdit', 'AREA_1': 'TextEdit', 'PERIMETE_1': 'TextEdit', 'HECTARES_1': 'TextEdit', 'SHAPE_LE_3': 'TextEdit', 'SHAPE_AR_3': 'TextEdit', 'FID_jalan1': 'TextEdit', 'LAYER': 'TextEdit', 'KETERANG_1': 'TextEdit', 'LENGTH_FEE': 'TextEdit', 'SHAPE_LE_4': 'TextEdit', 'SHAPE_LE_5': 'TextEdit', 'BUFF_DIS_1': 'TextEdit', 'ORIG_FID_1': 'TextEdit', });
lyr_sungai_buffer_1.set('fieldImages', {'FID_Bantul': 'TextEdit', 'PROVINSI': 'TextEdit', 'KODE_KAB': 'TextEdit', 'SHAPE_LENG': 'TextEdit', 'KODE_PROP': 'TextEdit', 'KABUPATEN': 'TextEdit', 'AREA': 'TextEdit', 'PERIMETER': 'TextEdit', 'HECTARES': 'TextEdit', 'SHAPE_LE_1': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'FID_penggu': 'TextEdit', 'FID_Peta_P': 'TextEdit', 'PL': 'TextEdit', 'Shape_Ar_1': 'TextEdit', 'Peruntukan': 'TextEdit', 'Keterangan': 'TextEdit', 'KW': 'TextEdit', 'WA': 'TextEdit', 'TA': 'TextEdit', 'DH': 'TextEdit', 'LU': 'TextEdit', 'KW_1': 'TextEdit', 'WA_1': 'TextEdit', 'TA_1': 'TextEdit', 'DH_1': 'TextEdit', 'SHAPE_Ar_2': 'TextEdit', 'BUFF_DIST': 'TextEdit', 'ORIG_FID': 'TextEdit', });
lyr_PL_bantul_2.set('fieldImages', {'FID_Bantul': 'TextEdit', 'PROVINSI': 'TextEdit', 'KODE_KAB': 'TextEdit', 'SHAPE_LENG': 'TextEdit', 'KODE_PROP': 'TextEdit', 'KABUPATEN': 'TextEdit', 'AREA': 'TextEdit', 'PERIMETER': 'TextEdit', 'HECTARES': 'TextEdit', 'SHAPE_LE_1': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'FID_penggu': 'TextEdit', 'FID_Peta_P': 'TextEdit', 'PL': 'TextEdit', 'Shape_Ar_1': 'TextEdit', 'Peruntukan': 'TextEdit', 'Keterangan': 'TextEdit', 'KW': 'TextEdit', 'WA': 'TextEdit', 'TA': 'TextEdit', 'DH': 'TextEdit', 'LU': 'TextEdit', 'KW_1': 'TextEdit', 'WA_1': 'TextEdit', 'TA_1': 'TextEdit', 'DH_1': 'TextEdit', 'SHAPE_Ar_2': 'TextEdit', 'BOBOT': 'TextEdit', 'BBT5': 'TextEdit', });
lyr_jalan_buffer_3.set('fieldImages', {'FID_Bantul': 'TextEdit', 'PROVINSI': 'TextEdit', 'KODE_KAB': 'TextEdit', 'SHAPE_LENG': 'TextEdit', 'KODE_PROP': 'TextEdit', 'KABUPATEN': 'TextEdit', 'AREA': 'TextEdit', 'PERIMETER': 'TextEdit', 'HECTARES': 'TextEdit', 'SHAPE_LE_1': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'FID_jalan_': 'TextEdit', 'LAYER': 'TextEdit', 'KETERANGAN': 'TextEdit', 'LENGTH_FEE': 'TextEdit', 'SHAPE_LE_2': 'TextEdit', 'SHAPE_LE_3': 'TextEdit', 'BUFF_DIST': 'TextEdit', 'ORIG_FID': 'TextEdit', });
lyr_jalan_bantul_4.set('fieldImages', {'FID_Bantul': 'TextEdit', 'PROVINSI': 'TextEdit', 'KODE_KAB': 'TextEdit', 'SHAPE_LENG': 'TextEdit', 'KODE_PROP': 'TextEdit', 'KABUPATEN': 'TextEdit', 'AREA': 'TextEdit', 'PERIMETER': 'TextEdit', 'HECTARES': 'TextEdit', 'SHAPE_LE_1': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'FID_jalan_': 'TextEdit', 'LAYER': 'TextEdit', 'KETERANGAN': 'TextEdit', 'LENGTH_FEE': 'TextEdit', 'SHAPE_LE_2': 'TextEdit', 'SHAPE_LE_3': 'TextEdit', });
lyr_Hasil_lokasi_5.set('fieldImages', {'FID_PL_ban': 'TextEdit', 'FID_Bantul': 'TextEdit', 'PROVINSI': 'TextEdit', 'KODE_KAB': 'TextEdit', 'SHAPE_LENG': 'TextEdit', 'KODE_PROP': 'TextEdit', 'KABUPATEN': 'TextEdit', 'AREA': 'TextEdit', 'PERIMETER': 'TextEdit', 'HECTARES': 'TextEdit', 'SHAPE_LE_1': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'FID_penggu': 'TextEdit', 'FID_Peta_P': 'TextEdit', 'PL': 'TextEdit', 'Shape_Ar_1': 'TextEdit', 'Peruntukan': 'TextEdit', 'Keterangan': 'TextEdit', 'KW': 'TextEdit', 'WA': 'TextEdit', 'TA': 'TextEdit', 'DH': 'TextEdit', 'LU': 'TextEdit', 'KW_1': 'TextEdit', 'WA_1': 'TextEdit', 'TA_1': 'TextEdit', 'DH_1': 'TextEdit', 'SHAPE_Ar_2': 'TextEdit', 'BOBOT': 'TextEdit', 'BBT5': 'TextEdit', 'FID_sungai': 'TextEdit', 'FID_sung_1': 'TextEdit', 'FID_Bant_1': 'TextEdit', 'PROVINSI_1': 'TextEdit', 'KODE_KAB_1': 'TextEdit', 'SHAPE_LE_2': 'TextEdit', 'KODE_PRO_1': 'TextEdit', 'KABUPATE_1': 'TextEdit', 'AREA_1': 'TextEdit', 'PERIMETE_1': 'TextEdit', 'HECTARES_1': 'TextEdit', 'SHAPE_LE_3': 'TextEdit', 'SHAPE_AR_3': 'TextEdit', 'FID_peng_1': 'TextEdit', 'FID_Peta_1': 'TextEdit', 'PL_1': 'TextEdit', 'Shape_Ar_4': 'TextEdit', 'Peruntuk_1': 'TextEdit', 'Keterang_1': 'TextEdit', 'KW_12': 'TextEdit', 'WA_12': 'TextEdit', 'TA_12': 'TextEdit', 'DH_12': 'TextEdit', 'LU_1': 'TextEdit', 'KW_12_13': 'TextEdit', 'WA_12_13': 'TextEdit', 'TA_12_13': 'TextEdit', 'DH_12_13': 'TextEdit', 'SHAPE_Ar_5': 'TextEdit', 'BUFF_DIST': 'TextEdit', 'ORIG_FID': 'TextEdit', 'FID_jalan_': 'TextEdit', 'FID_Bant_2': 'TextEdit', 'PROVINSI_2': 'TextEdit', 'KODE_KAB_2': 'TextEdit', 'SHAPE_LE_4': 'TextEdit', 'KODE_PRO_2': 'TextEdit', 'KABUPATE_2': 'TextEdit', 'AREA_12': 'TextEdit', 'PERIMETE_2': 'TextEdit', 'HECTARES_2': 'TextEdit', 'SHAPE_LE_5': 'TextEdit', 'SHAPE_AR_6': 'TextEdit', 'FID_jalan1': 'TextEdit', 'LAYER': 'TextEdit', 'KETERANG_2': 'TextEdit', 'LENGTH_FEE': 'TextEdit', 'SHAPE_LE_6': 'TextEdit', 'SHAPE_LE_7': 'TextEdit', 'BUFF_DIS_1': 'TextEdit', 'ORIG_FID_1': 'TextEdit', });
lyr_bufferjln_6.set('fieldImages', {'FID_Bantul': 'TextEdit', 'PROVINSI': 'TextEdit', 'KODE_KAB': 'TextEdit', 'SHAPE_LENG': 'TextEdit', 'KODE_PROP': 'TextEdit', 'KABUPATEN': 'TextEdit', 'AREA': 'TextEdit', 'PERIMETER': 'TextEdit', 'HECTARES': 'TextEdit', 'SHAPE_LE_1': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'FID_jalan_': 'TextEdit', 'LAYER': 'TextEdit', 'KETERANGAN': 'TextEdit', 'LENGTH_FEE': 'TextEdit', 'SHAPE_LE_2': 'TextEdit', 'SHAPE_LE_3': 'TextEdit', });
lyr_buffer_jalan_7.set('fieldImages', {'FID_Bantul': 'TextEdit', 'PROVINSI': 'TextEdit', 'KODE_KAB': 'TextEdit', 'SHAPE_LENG': 'TextEdit', 'KODE_PROP': 'TextEdit', 'KABUPATEN': 'TextEdit', 'AREA': 'TextEdit', 'PERIMETER': 'TextEdit', 'HECTARES': 'TextEdit', 'SHAPE_LE_1': 'TextEdit', 'SHAPE_AREA': 'TextEdit', 'FID_jalan_': 'TextEdit', 'LAYER': 'TextEdit', 'KETERANGAN': 'TextEdit', 'LENGTH_FEE': 'TextEdit', 'SHAPE_LE_2': 'TextEdit', 'SHAPE_LE_3': 'TextEdit', 'BUFF_DIST': 'TextEdit', 'ORIG_FID': 'TextEdit', });
lyr_sungai_int_jalan_0.set('fieldLabels', {'FID_sungai': 'no label', 'FID_Bantul': 'no label', 'PROVINSI': 'no label', 'KODE_KAB': 'no label', 'SHAPE_LENG': 'no label', 'KODE_PROP': 'no label', 'KABUPATEN': 'no label', 'AREA': 'no label', 'PERIMETER': 'no label', 'HECTARES': 'no label', 'SHAPE_LE_1': 'no label', 'SHAPE_AREA': 'no label', 'FID_penggu': 'no label', 'FID_Peta_P': 'no label', 'PL': 'no label', 'Shape_Ar_1': 'no label', 'Peruntukan': 'no label', 'Keterangan': 'no label', 'KW': 'no label', 'WA': 'no label', 'TA': 'no label', 'DH': 'no label', 'LU': 'no label', 'KW_1': 'no label', 'WA_1': 'no label', 'TA_1': 'no label', 'DH_1': 'no label', 'SHAPE_Ar_2': 'no label', 'BUFF_DIST': 'no label', 'ORIG_FID': 'no label', 'FID_jalan_': 'no label', 'FID_Bant_1': 'no label', 'PROVINSI_1': 'no label', 'KODE_KAB_1': 'no label', 'SHAPE_LE_2': 'no label', 'KODE_PRO_1': 'no label', 'KABUPATE_1': 'no label', 'AREA_1': 'no label', 'PERIMETE_1': 'no label', 'HECTARES_1': 'no label', 'SHAPE_LE_3': 'no label', 'SHAPE_AR_3': 'no label', 'FID_jalan1': 'no label', 'LAYER': 'no label', 'KETERANG_1': 'no label', 'LENGTH_FEE': 'no label', 'SHAPE_LE_4': 'no label', 'SHAPE_LE_5': 'no label', 'BUFF_DIS_1': 'no label', 'ORIG_FID_1': 'no label', });
lyr_sungai_buffer_1.set('fieldLabels', {'FID_Bantul': 'no label', 'PROVINSI': 'no label', 'KODE_KAB': 'no label', 'SHAPE_LENG': 'no label', 'KODE_PROP': 'no label', 'KABUPATEN': 'no label', 'AREA': 'no label', 'PERIMETER': 'no label', 'HECTARES': 'no label', 'SHAPE_LE_1': 'no label', 'SHAPE_AREA': 'no label', 'FID_penggu': 'no label', 'FID_Peta_P': 'no label', 'PL': 'no label', 'Shape_Ar_1': 'no label', 'Peruntukan': 'no label', 'Keterangan': 'no label', 'KW': 'no label', 'WA': 'no label', 'TA': 'no label', 'DH': 'no label', 'LU': 'no label', 'KW_1': 'no label', 'WA_1': 'no label', 'TA_1': 'no label', 'DH_1': 'no label', 'SHAPE_Ar_2': 'no label', 'BUFF_DIST': 'no label', 'ORIG_FID': 'no label', });
lyr_PL_bantul_2.set('fieldLabels', {'FID_Bantul': 'no label', 'PROVINSI': 'no label', 'KODE_KAB': 'no label', 'SHAPE_LENG': 'no label', 'KODE_PROP': 'no label', 'KABUPATEN': 'no label', 'AREA': 'no label', 'PERIMETER': 'no label', 'HECTARES': 'no label', 'SHAPE_LE_1': 'no label', 'SHAPE_AREA': 'no label', 'FID_penggu': 'no label', 'FID_Peta_P': 'no label', 'PL': 'no label', 'Shape_Ar_1': 'no label', 'Peruntukan': 'no label', 'Keterangan': 'no label', 'KW': 'no label', 'WA': 'no label', 'TA': 'no label', 'DH': 'no label', 'LU': 'no label', 'KW_1': 'no label', 'WA_1': 'no label', 'TA_1': 'no label', 'DH_1': 'no label', 'SHAPE_Ar_2': 'no label', 'BOBOT': 'no label', 'BBT5': 'no label', });
lyr_jalan_buffer_3.set('fieldLabels', {'FID_Bantul': 'no label', 'PROVINSI': 'no label', 'KODE_KAB': 'no label', 'SHAPE_LENG': 'no label', 'KODE_PROP': 'no label', 'KABUPATEN': 'no label', 'AREA': 'no label', 'PERIMETER': 'no label', 'HECTARES': 'no label', 'SHAPE_LE_1': 'no label', 'SHAPE_AREA': 'no label', 'FID_jalan_': 'no label', 'LAYER': 'no label', 'KETERANGAN': 'no label', 'LENGTH_FEE': 'no label', 'SHAPE_LE_2': 'no label', 'SHAPE_LE_3': 'no label', 'BUFF_DIST': 'no label', 'ORIG_FID': 'no label', });
lyr_jalan_bantul_4.set('fieldLabels', {'FID_Bantul': 'no label', 'PROVINSI': 'no label', 'KODE_KAB': 'no label', 'SHAPE_LENG': 'no label', 'KODE_PROP': 'no label', 'KABUPATEN': 'no label', 'AREA': 'no label', 'PERIMETER': 'no label', 'HECTARES': 'no label', 'SHAPE_LE_1': 'no label', 'SHAPE_AREA': 'no label', 'FID_jalan_': 'no label', 'LAYER': 'no label', 'KETERANGAN': 'no label', 'LENGTH_FEE': 'no label', 'SHAPE_LE_2': 'no label', 'SHAPE_LE_3': 'no label', });
lyr_Hasil_lokasi_5.set('fieldLabels', {'FID_PL_ban': 'no label', 'FID_Bantul': 'no label', 'PROVINSI': 'no label', 'KODE_KAB': 'no label', 'SHAPE_LENG': 'no label', 'KODE_PROP': 'no label', 'KABUPATEN': 'no label', 'AREA': 'no label', 'PERIMETER': 'no label', 'HECTARES': 'no label', 'SHAPE_LE_1': 'no label', 'SHAPE_AREA': 'no label', 'FID_penggu': 'no label', 'FID_Peta_P': 'no label', 'PL': 'no label', 'Shape_Ar_1': 'no label', 'Peruntukan': 'no label', 'Keterangan': 'no label', 'KW': 'no label', 'WA': 'no label', 'TA': 'no label', 'DH': 'no label', 'LU': 'no label', 'KW_1': 'no label', 'WA_1': 'no label', 'TA_1': 'no label', 'DH_1': 'no label', 'SHAPE_Ar_2': 'no label', 'BOBOT': 'no label', 'BBT5': 'no label', 'FID_sungai': 'no label', 'FID_sung_1': 'no label', 'FID_Bant_1': 'no label', 'PROVINSI_1': 'no label', 'KODE_KAB_1': 'no label', 'SHAPE_LE_2': 'no label', 'KODE_PRO_1': 'no label', 'KABUPATE_1': 'no label', 'AREA_1': 'no label', 'PERIMETE_1': 'no label', 'HECTARES_1': 'no label', 'SHAPE_LE_3': 'no label', 'SHAPE_AR_3': 'no label', 'FID_peng_1': 'no label', 'FID_Peta_1': 'no label', 'PL_1': 'no label', 'Shape_Ar_4': 'no label', 'Peruntuk_1': 'no label', 'Keterang_1': 'no label', 'KW_12': 'no label', 'WA_12': 'no label', 'TA_12': 'no label', 'DH_12': 'no label', 'LU_1': 'no label', 'KW_12_13': 'no label', 'WA_12_13': 'no label', 'TA_12_13': 'no label', 'DH_12_13': 'no label', 'SHAPE_Ar_5': 'no label', 'BUFF_DIST': 'no label', 'ORIG_FID': 'no label', 'FID_jalan_': 'no label', 'FID_Bant_2': 'no label', 'PROVINSI_2': 'no label', 'KODE_KAB_2': 'no label', 'SHAPE_LE_4': 'no label', 'KODE_PRO_2': 'no label', 'KABUPATE_2': 'no label', 'AREA_12': 'no label', 'PERIMETE_2': 'no label', 'HECTARES_2': 'no label', 'SHAPE_LE_5': 'no label', 'SHAPE_AR_6': 'no label', 'FID_jalan1': 'no label', 'LAYER': 'no label', 'KETERANG_2': 'no label', 'LENGTH_FEE': 'no label', 'SHAPE_LE_6': 'no label', 'SHAPE_LE_7': 'no label', 'BUFF_DIS_1': 'no label', 'ORIG_FID_1': 'no label', });
lyr_bufferjln_6.set('fieldLabels', {'FID_Bantul': 'no label', 'PROVINSI': 'no label', 'KODE_KAB': 'no label', 'SHAPE_LENG': 'no label', 'KODE_PROP': 'no label', 'KABUPATEN': 'no label', 'AREA': 'no label', 'PERIMETER': 'no label', 'HECTARES': 'no label', 'SHAPE_LE_1': 'no label', 'SHAPE_AREA': 'no label', 'FID_jalan_': 'no label', 'LAYER': 'no label', 'KETERANGAN': 'no label', 'LENGTH_FEE': 'no label', 'SHAPE_LE_2': 'no label', 'SHAPE_LE_3': 'no label', });
lyr_buffer_jalan_7.set('fieldLabels', {'FID_Bantul': 'no label', 'PROVINSI': 'no label', 'KODE_KAB': 'no label', 'SHAPE_LENG': 'no label', 'KODE_PROP': 'no label', 'KABUPATEN': 'no label', 'AREA': 'no label', 'PERIMETER': 'no label', 'HECTARES': 'no label', 'SHAPE_LE_1': 'no label', 'SHAPE_AREA': 'no label', 'FID_jalan_': 'no label', 'LAYER': 'no label', 'KETERANGAN': 'no label', 'LENGTH_FEE': 'no label', 'SHAPE_LE_2': 'no label', 'SHAPE_LE_3': 'no label', 'BUFF_DIST': 'no label', 'ORIG_FID': 'no label', });
lyr_buffer_jalan_7.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});